[package]
name = "quaigh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

authors = ["Gabriel Gouvine <gabriel.gouvine_cargo@m4x.org>"]
description = "mplementation of And-Inverter-Graph (AIG) for logic simplification"
license = "MIT OR Apache-2.0"
keywords = ["boolean function", "logic function", "aig"]

[dependencies]
