on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


name: Test

jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        features: [""]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: rustup component add rustfmt

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Readme
        run: |
          cargo install cargo-rdme
          cargo rdme --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output
